spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_sms
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: gulimail-member
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpathï¼šmapper/**/*.xml
  global-config:
      db-config:
        id-type: auto
server:
  port: 8000
