spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_oms
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpathï¼šmapper/**/*.xml
  global-config:
      db-config:
        id-type: auto
server:
  port: 9000